/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as NewRouteImport } from './routes/new'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as FreeAiIndexRouteImport } from './routes/free-ai.index'
import { Route as FreeAiTypeRouteImport } from './routes/free-ai.$type'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAiIndexRoute = FreeAiIndexRouteImport.update({
  id: '/free-ai/',
  path: '/free-ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAiTypeRoute = FreeAiTypeRouteImport.update({
  id: '/free-ai/$type',
  path: '/free-ai/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/popular': typeof PopularRoute
  '/category/$slug': typeof CategorySlugRoute
  '/free-ai/$type': typeof FreeAiTypeRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/free-ai/': typeof FreeAiIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/popular': typeof PopularRoute
  '/category/$slug': typeof CategorySlugRoute
  '/free-ai/$type': typeof FreeAiTypeRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/free-ai': typeof FreeAiIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/popular': typeof PopularRoute
  '/category/$slug': typeof CategorySlugRoute
  '/free-ai/$type': typeof FreeAiTypeRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/free-ai/': typeof FreeAiIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/compare'
    | '/favorites'
    | '/new'
    | '/popular'
    | '/category/$slug'
    | '/free-ai/$type'
    | '/guides/$slug'
    | '/tools/$slug'
    | '/free-ai/'
    | '/guides/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/compare'
    | '/favorites'
    | '/new'
    | '/popular'
    | '/category/$slug'
    | '/free-ai/$type'
    | '/guides/$slug'
    | '/tools/$slug'
    | '/free-ai'
    | '/guides'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/compare'
    | '/favorites'
    | '/new'
    | '/popular'
    | '/category/$slug'
    | '/free-ai/$type'
    | '/guides/$slug'
    | '/tools/$slug'
    | '/free-ai/'
    | '/guides/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  NewRoute: typeof NewRoute
  PopularRoute: typeof PopularRoute
  CategorySlugRoute: typeof CategorySlugRoute
  FreeAiTypeRoute: typeof FreeAiTypeRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  FreeAiIndexRoute: typeof FreeAiIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-ai/': {
      id: '/free-ai/'
      path: '/free-ai'
      fullPath: '/free-ai/'
      preLoaderRoute: typeof FreeAiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-ai/$type': {
      id: '/free-ai/$type'
      path: '/free-ai/$type'
      fullPath: '/free-ai/$type'
      preLoaderRoute: typeof FreeAiTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  NewRoute: NewRoute,
  PopularRoute: PopularRoute,
  CategorySlugRoute: CategorySlugRoute,
  FreeAiTypeRoute: FreeAiTypeRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  FreeAiIndexRoute: FreeAiIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
